baseURL: "https://example.com"
languageCode: "en-us"
title: "leanfield.io"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/PJGeutjens"
  github: "https://github.com/pjgeutjens"
  linkedin: "https://www.linkedin.com/in/pieterjangeutjens/"
taxonomies:
  author: authors
